Repository oakleywindiate/rancid-tomatillos-wo, pull requests merged in 2022-05, with the labels that each got.

#11 Setup/app.js/ow
  src/App.css
  src/App.js
  src/Movies.css
  src/Movies.js
  src/Tile.css
  src/Tile.js
  src/movieData.js
Labels: enhancement, MVP, setup

#14 Feature/movie display part2/ow
  src/App.js
  src/Details.css
  src/Details.js
  src/Movies.js
Labels: user stories, MVP, setup

#15 Fix button functionality to go back to all movies
  src/App.js
  src/DetailTile.js
  src/Details.js
  src/Movies.js
  src/Tile.js
Labels: user stories, MVP, setup

#18 Add CSS to tiles
  src/DetailTile.css
  src/DetailTile.js
  src/Tile.css
  src/Tile.js
Labels: CSS

#21 Feature/api/ow
  src/App.js
  src/DetailTile.js
  src/Details.js
  src/Movies.js
  src/apiCalls.js
Labels: user stories, setup, API

#25 Add Cypress Functionality and Wrote Cypress Tests
  cypress.json
  cypress/fixtures/example.json
  cypress/integration/homeView_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  package-lock.json
  package.json
  src/DetailTile.js
Labels: testing suite

#27 Refactor/cypress/add interceptors/ow
  cypress/fixtures/example.json
  cypress/fixtures/movie.json
  cypress/fixtures/movieData.json
  cypress/integration/homeView_spec.js
Labels: refactor, testing suite

#28 Feature/router/wp
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/DetailTile.js
  src/Tile.js
  src/index.js
Labels: MVP, router

#40 Refactor/api calls/ow
  src/DetailTile.js
  src/apiCalls.js
Labels: bug, enhancement, API

#42 Feature/css part2/ow
  README.md
  src/DetailTile.css
  src/DetailTile.js
Labels: CSS

#47 Feature/add more search/wp
  src/App.css
  src/App.js
  src/DetailTile.css
  src/DetailTile.js
  src/Details.js
  src/Form.css
  src/Form.js
  src/Movies.css
  src/Movies.js
  src/Tile.js
  src/index.css
Labels: bug, MVP, CSS

#50 Add testing file and functionality for search tests
  cypress/integration/movieDetailView_spec.js
  cypress/integration/searchView_spec.js
  src/Form.js
Labels: testing suite

#51 Feature/search error response/ow
  src/App.js
  src/Form.css
  src/Form.js
Labels: bug, CSS

#53 Refactor/all files/ow
  cypress/integration/homeView_spec.js
  cypress/integration/searchView_spec.js
  public/logo192.png
  public/logo512.png
  src/App.css
  src/App.js
  src/DetailTile.js
  src/Details.css
  src/Form.css
  src/Form.js
  src/Movies.css
  src/Movies.js
  src/SearchMovies.css
  src/SearchMovies.js
  src/Tile.css
  src/Tile.js
  src/index.css
  src/index.js
  src/logo.svg
  src/movieData.js
Labels: refactor

#54 Write ReadMe
  README.md
Labels: documentation

#55 Refactor/additional refactor
  README.md
  cypress/integration/homeView_spec.js
  cypress/integration/movieDetailView_spec.js
  cypress/integration/searchView_spec.js
  src/App.css
  src/DetailTile.js
  src/SearchMovies.js
Labels: bug
